from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

SKIP_DIRS = {
    ".git",
    ".venv",
    "dataset",
    "env",
    "models",
    "outputs",
    "release",
    "reports",
    "research_runs",
    "sample_out",
    "smoke_dataset",
}

TEXT_SUFFIXES = {
    ".dockerignore",
    ".gitignore",
    ".gitattributes",
    ".json",
    ".md",
    ".ps1",
    ".py",
    ".txt",
    ".yaml",
    ".yml",
}

BANNED_PHRASES = tuple(
    "".join(parts)
    for parts in (
        ("AI-", "generated"),
        ("AI ", "agent"),
        ("AI ", "tool"),
        ("Chat", "GPT"),
        ("Clau", "de"),
        ("Gem", "ini"),
        ("Co", "pilot"),
        ("Co", "dex"),
        ("Prompt", "LLM", "Agent"),
        ("Qo", "do"),
        ("assis", "tant"),
        ("generated by ", "AI"),
        ("llm", "_adapter"),
    )
)

BANNED_PATH_PARTS = {"." + "qodo"}
GENERATED_PATH_PARTS = {"__pycache__"}
GENERATED_SUFFIXES = {".pyc", ".pyo", ".pyd"}
GENERATED_NAMES = {"requirements-research.txt"}
LOG_SUFFIX = ".log"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check repository hygiene for client delivery")
    parser.add_argument("--root", default=ROOT, type=Path)
    parser.add_argument("--json-out", default=None, type=Path)
    return parser.parse_args()


def is_skipped(relative: Path) -> bool:
    return any(part in SKIP_DIRS for part in relative.parts)


def should_scan(path: Path, root: Path) -> bool:
    relative = path.relative_to(root)
    if is_skipped(relative):
        return False
    if path.name == "check_repo_hygiene.py":
        return False
    if path.name == "Dockerfile":
        return True
    return path.suffix.lower() in TEXT_SUFFIXES


def path_findings(root: Path) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    for path in root.rglob("*"):
        relative = path.relative_to(root)
        if is_skipped(relative):
            continue
        parts = set(relative.parts)
        if parts & GENERATED_PATH_PARTS or path.suffix.lower() in GENERATED_SUFFIXES or path.name in GENERATED_NAMES:
            findings.append(
                {
                    "path": str(relative),
                    "line": "",
                    "phrase": path.name,
                    "detail": "Remove generated runtime artifacts from the deliverable repository.",
                }
            )
            continue
        if path.is_file() and path.suffix.lower() == LOG_SUFFIX:
            findings.append(
                {
                    "path": str(relative),
                    "line": "",
                    "phrase": path.suffix,
                    "detail": "Remove local log files from the deliverable repository.",
                }
            )
            continue
        for part in relative.parts:
            if part in BANNED_PATH_PARTS:
                findings.append(
                    {
                        "path": str(relative),
                        "line": "",
                        "phrase": part,
                        "detail": "Remove local tool metadata directories from the deliverable repository.",
                    }
                )
    return findings


def content_findings(root: Path) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    for path in root.rglob("*"):
        if not path.is_file() or not should_scan(path, root):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        relative = path.relative_to(root)
        for line_number, line in enumerate(text.splitlines(), start=1):
            for phrase in BANNED_PHRASES:
                if phrase in line:
                    findings.append(
                        {
                            "path": str(relative),
                            "line": str(line_number),
                            "phrase": phrase,
                            "detail": line.strip()[:240],
                        }
                    )
    return findings


def main() -> None:
    args = parse_args()
    root = args.root.resolve()
    findings = path_findings(root) + content_findings(root)
    payload = {
        "status": "PASS" if not findings else "FAIL",
        "root": str(root),
        "findings": findings,
    }
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(payload, indent=2, sort_keys=True))
    if findings:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
